---
kind: Service
apiVersion: v1
metadata:
  name: testbackendapi
  namespace:  test
spec:
  selector:
    app: mytestappbe
    tier:  test
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
