---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mytestappbe-deployment
  namespace:  test
spec:
  selector:
    matchLabels:
      app: mytestappbe
  replicas: 2
  minReadySeconds:  5
  progressDeadlineSeconds:  300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge:  50%
      maxUnavailable:  50%
  template: 
    metadata:
      labels: 
        app: mytestappbe
        tier:  backend
    spec:
      containers:
      - name: mytestappbe
         image: khalindar/mydockerappbe0903:2.0
         imagePullPolicy:  Always  
         ports:
         - containerPort: 80
         resources:
           limits:
             cpu: "0.5"
             memory: "500Mi"
           requests:
             cpu: "0.2"